platform:
  - x86
  - x64
install:
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  # Typical npm stuff.
  - npm install yarn
  - yarn
build:
  - yarn dist
